# Generated by Django 5.1.6 on 2025-02-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('dob', models.CharField(max_length=18)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('course', models.CharField(choices=[('django', 'django'), ('testing', 'testing'), ('datascience', 'datascience'), ('machine learning', 'machine learning'), ('java spring', 'java spring'), ('asp.net', 'asp.net'), ('flutter', 'flutter')], default='django', max_length=200)),
                ('passout_year', models.CharField(max_length=200)),
                ('course_mode', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('hybrid', 'hybrid')], default='offline', max_length=200)),
                ('source', models.CharField(choices=[('website', 'website'), ('socialmedia', 'socialmedia'), ('referral', 'referral'), ('walkin', 'walkin'), ('education fair', 'education fair'), ('adv', 'adv')], default='website', max_length=200)),
                ('status', models.CharField(choices=[('new', 'new'), ('qualified', 'qualified'), ('unqualified', 'unqualified'), ('proceed to admission', 'proceed to admission')], default='new', max_length=200)),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=200)),
                ('note', models.TextField(null=True)),
                ('follow_up_date', models.CharField(max_length=200)),
            ],
        ),
    ]
